param(
    [string]$ProjectRoot = "C:\Users\ryujo\urbanbus_rl_project",
    [switch]$RunSelfTest
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $ProjectRoot)) {
    throw "[STOP] Project root not found: $ProjectRoot"
}
Set-Location $ProjectRoot

$AdaptersDir = ".\05_training\adapters"
New-Item -ItemType Directory -Force -Path $AdaptersDir | Out-Null

# ---------------------------------------------------------------------
# Step 97 file 1:
# 05_training/adapters/tensor_signal_data_requirements_v2.json
# ---------------------------------------------------------------------
$RequirementsJson = @'
{
  "artifact_version": "tensor_signal_data_requirements_v2",
  "step": 97,
  "title": "Tensor DB + signal CSV data availability audit",
  "status": "draft_contract",
  "claim_guardrails": {
    "trained_model": false,
    "performance_claim_allowed": false,
    "smoke_training_only": true,
    "smoke_evaluation_only": true,
    "matrix_smoke_evaluation_only": true,
    "causal_performance_claim_allowed": false,
    "daegu_citywide_performance_claim_allowed": false,
    "fleet_reduction_claim_allowed": false
  },
  "source_classes": {
    "tensor_db_direct": {
      "description": "Features already present in the tensor database or PyG dataset artifacts.",
      "allowed_for_causal_simulator_v2": true,
      "allowed_usage": [
        "static graph skeleton",
        "observed demand context",
        "time context",
        "edge distance/time/cost context",
        "baseline scenario indexing",
        "non-causal smoke validation metadata"
      ],
      "examples": [
        "node_uid",
        "node_index",
        "src_idx",
        "dst_idx",
        "distance_m",
        "time_sec",
        "generalized_cost",
        "long_edge_5km_flag",
        "boardings_recent_log",
        "alightings_recent_log",
        "waiting_passenger_cnt_log",
        "hour_sin",
        "hour_cos",
        "is_peak",
        "next_boardings_recent",
        "next_alightings_recent",
        "next_waiting_passenger_cnt",
        "state_ts",
        "next_state_ts",
        "time_band",
        "service_date",
        "window_id"
      ]
    },
    "signal_csv_direct": {
      "description": "Fields directly obtainable from the Daegu traffic signal CSV without simulation.",
      "allowed_for_causal_simulator_v2": true,
      "allowed_usage": [
        "static signal infrastructure feature",
        "node/edge neighborhood signal inventory",
        "spatial complexity proxy"
      ],
      "examples": [
        "signal_id",
        "signal_type",
        "signal_name",
        "latitude",
        "longitude",
        "x_coord",
        "y_coord",
        "pedestrian_signal_flag",
        "blink_signal_flag",
        "controlled_signal_flag",
        "installation_location"
      ],
      "notes": [
        "Column names may differ by CSV source. The inspector script infers likely columns from multiple candidate names.",
        "Direct signal CSV fields must not be interpreted as dynamic signal phases."
      ]
    },
    "tensor_db_plus_signal_csv_derived": {
      "description": "Features generated by joining tensor DB graph nodes/edges with static signal infrastructure locations.",
      "allowed_for_causal_simulator_v2": true,
      "allowed_usage": [
        "static node feature extension",
        "static edge feature extension",
        "causal simulator context feature",
        "policy observation context only"
      ],
      "examples": [
        "signal_count_within_100m",
        "signal_count_within_250m",
        "signal_count_within_500m",
        "signal_density_per_km",
        "nearest_signal_distance_m",
        "pedestrian_signal_count_within_250m",
        "blink_signal_ratio_within_250m",
        "controlled_signal_ratio_within_250m",
        "edge_signal_count",
        "edge_signal_density_per_km",
        "edge_nearest_signal_distance_m"
      ]
    },
    "proxy_only": {
      "description": "Quantities that may be represented only as coarse proxies, not as directly observed causal mechanisms.",
      "allowed_for_causal_simulator_v2": true,
      "allowed_usage": [
        "weak prior",
        "environment difficulty proxy",
        "route complexity proxy",
        "context feature with explicit proxy marker"
      ],
      "must_mark_columns_with": "_proxy",
      "examples": [
        "intersection_complexity_proxy",
        "signal_delay_risk_proxy",
        "stop_access_friction_proxy",
        "edge_control_complexity_proxy"
      ],
      "warnings": [
        "These features must not be reported as measured red-light delay or measured signal timing.",
        "Proxy features may help policy conditioning but cannot support standalone traffic-signal causal claims."
      ]
    },
    "currently_unavailable": {
      "description": "Data not available from current tensor DB and static signal CSV.",
      "allowed_for_causal_simulator_v2": false,
      "examples": [
        "red_light_delay_seconds",
        "green_time_seconds",
        "cycle_length_seconds",
        "phase_sequence",
        "signal_offset_seconds",
        "real_time_signal_state",
        "queue_discharge_rate",
        "lane_level_turning_movement",
        "actual_vehicle_trajectory",
        "actual_bus_arrival_second_level",
        "incident_event_stream",
        "weather_event_stream"
      ],
      "hard_rule": "Do not synthesize these as if observed. If used later, they require new data source, calibrated simulator, or explicit synthetic assumption document."
    }
  },
  "causal_simulator_v2_admission_rules": {
    "admit": [
      "tensor_db_direct",
      "signal_csv_direct",
      "tensor_db_plus_signal_csv_derived",
      "proxy_only_with_explicit_proxy_suffix"
    ],
    "reject": [
      "currently_unavailable",
      "dynamic_signal_phase_claims",
      "red_light_delay_claims_without_phase_data",
      "fleet_reduction_performance_claims_from_toy_or_smoke_runs"
    ]
  },
  "step_98_signal_feature_builder_contract_draft": {
    "script_name": "build_signal_features_for_causal_simulator_v2.py",
    "inputs": {
      "signal_csv": {
        "required": true,
        "format": "csv",
        "encoding_candidates": ["utf-8-sig", "utf-8", "cp949", "euc-kr"]
      },
      "tensor_node_table_or_file": {
        "required": true,
        "examples": [
          "public.gatv2_node_master_active",
          "node_master.parquet"
        ]
      },
      "tensor_edge_table_or_file": {
        "required": true,
        "examples": [
          "public.gatv2_edge_primary_active",
          "edge_primary.parquet"
        ]
      },
      "coordinate_reference": {
        "required": true,
        "allowed_values": [
          "EPSG:4326",
          "EPSG:5187",
          "unknown_requires_manual_mapping"
        ]
      }
    },
    "outputs": {
      "node_signal_features": {
        "format": "parquet",
        "required_columns": [
          "node_uid",
          "node_index",
          "signal_count_250m",
          "nearest_signal_distance_m",
          "pedestrian_signal_count_250m",
          "blink_signal_ratio_250m",
          "controlled_signal_ratio_250m",
          "signal_feature_quality_flag"
        ]
      },
      "edge_signal_features": {
        "format": "parquet",
        "required_columns": [
          "src_idx",
          "dst_idx",
          "edge_signal_count",
          "edge_signal_density_per_km",
          "edge_nearest_signal_distance_m",
          "edge_signal_feature_quality_flag"
        ]
      },
      "feature_contract_json": {
        "format": "json",
        "must_include": [
          "source_csv_path",
          "source_csv_hash",
          "coordinate_reference",
          "join_method",
          "feature_definitions",
          "unavailable_dynamic_signal_fields"
        ]
      }
    }
  }
}
'@

$RequirementsPath = Join-Path $AdaptersDir "tensor_signal_data_requirements_v2.json"
$RequirementsJson | Set-Content -Path $RequirementsPath -Encoding UTF8

# ---------------------------------------------------------------------
# Step 97 file 2:
# 05_training/adapters/tensor_signal_data_availability_audit.md
# ---------------------------------------------------------------------
$AuditMd = @'
# Step 97 — Tensor DB + Signal CSV Data Availability Audit

## 0. 목적

이 문서는 `causal simulator v2` 계약을 바로 작성하기 전에, 현재 사용 가능한 데이터의 한계를 먼저 고정하기 위한 audit 문서이다.

핵심 질문은 다음이다.

1. 현재 tensor DB(Database=데이터베이스)에 직접 존재하는 데이터는 무엇인가?
2. 대구 신호등 CSV(Comma-Separated Values=쉼표 구분값)에서 직접 얻을 수 있는 데이터는 무엇인가?
3. tensor DB + signal CSV 결합으로 생성 가능한 feature는 무엇인가?
4. proxy로만 가능한 데이터는 무엇인가?
5. 현재 절대 만들 수 없는 데이터는 무엇인가?
6. causal simulator v2에 넣어도 되는 데이터와 넣으면 안 되는 데이터는 무엇인가?

---

## 1. 현재 claim guardrail

현재 결과는 toy causal smoke validation이다.

| 항목 | 값 |
|---|---|
| `trained_model` | `false` |
| `performance_claim_allowed` | `false` |
| `smoke_training_only` | `true` |
| `smoke_evaluation_only` | `true` |
| `matrix_smoke_evaluation_only` | `true` |
| 논문 성능 주장 | 금지 |
| 대구 전역 성능 주장 | 금지 |
| 실제 fleet reduction 주장 | 금지 |

따라서 Step 97의 산출물도 **성능 증명 문서가 아니라 데이터 사용 가능성 분류 문서**이다.

---

## 2. Tensor DB에 직접 존재하는 데이터

현재 GATv2(Graph Attention Network version 2=그래프 어텐션 네트워크 버전 2) / MAPPO(Multi-Agent Proximal Policy Optimization=다중 에이전트 근접 정책 최적화) 경로에서 직접 사용할 수 있는 데이터는 아래와 같다.

### 2.1 Node identity / graph population

| 데이터 | 사용 가능성 | 설명 |
|---|---|---|
| `node_uid` | 직접 가능 | 정류장 노드 고유 ID(Identifier=식별자) |
| `node_index` | 직접 가능 | PyG(PyTorch Geometric=파이토치 지오메트릭) dense index |
| `num_nodes` | 직접 가능 | 현재 canonical 기준 4,116 노드 |
| node mask | 직접 가능 | 관측 row가 없는 노드 구분 |

### 2.2 Static edge skeleton

| 데이터 | 사용 가능성 | 설명 |
|---|---|---|
| `src_idx` | 직접 가능 | edge source node index |
| `dst_idx` | 직접 가능 | edge destination node index |
| `distance_m` | 직접 가능 | 정류장 간 거리 |
| `time_sec` | 직접 가능 | 평균 속도 가정 기반 이동 시간 |
| `generalized_cost` | 직접 가능 | graph edge cost |
| `long_edge_5km_flag` | 직접 가능 | 장거리 edge flag |

### 2.3 Snapshot demand / time context

| 데이터 | 사용 가능성 | 설명 |
|---|---|---|
| `boardings_recent_log` | 직접 가능 | 현재 승차 수요 log feature |
| `alightings_recent_log` | 직접 가능 | 현재 하차 수요 log feature |
| `waiting_passenger_cnt_log` | 직접 가능 | 현재 대기 승객 log feature |
| `hour_sin` | 직접 가능 | 시간 cyclic encoding |
| `hour_cos` | 직접 가능 | 시간 cyclic encoding |
| `is_peak` | 직접 가능 | 첨두 여부 |
| `next_boardings_recent` | 직접 가능 | supervised target |
| `next_alightings_recent` | 직접 가능 | supervised target |
| `next_waiting_passenger_cnt` | 직접 가능 | supervised target |

### 2.4 Scenario / evaluation context

| 데이터 | 사용 가능성 | 설명 |
|---|---|---|
| `state_ts` | 직접 가능 | 상태 시각 |
| `next_state_ts` | 직접 가능 | 다음 관측 시각 |
| `service_date` | 직접 가능 | 운행일 |
| `time_band` | 직접 가능 | peak/offpeak/night |
| `window_id` | 직접 가능 | 평가 window index |
| 12-KPI schema | 부분 가능 | toy causal smoke pipeline 기준으로 schema 확장됨 |

---

## 3. Signal CSV에서 직접 얻을 수 있는 데이터

신호등 CSV는 **동적 신호 phase simulation 원천이 아니라 정적 signal infrastructure source**로 취급한다.

### 3.1 직접 사용 가능한 후보

| 데이터 | 사용 가능성 | 설명 |
|---|---|---|
| signal ID | 직접 가능 | 신호등 개체 식별자 |
| signal name/type | 직접 가능 | 신호등 명칭 또는 종류 |
| latitude/longitude | 직접 가능 | 위경도 좌표가 있는 경우 |
| x/y projected coordinate | 직접 가능 | EPSG:5187 등 투영 좌표가 있는 경우 |
| pedestrian signal flag | 직접 가능 | 보행자 신호 여부가 컬럼으로 있거나 type에서 추론 가능한 경우 |
| blink signal flag | 직접 가능 | 점멸 신호 여부 |
| controlled signal flag | 직접 가능 | 제어 신호 여부 |
| installation location | 직접 가능 | 설치 위치 텍스트 |

### 3.2 직접 사용하면 안 되는 해석

CSV에 신호등 위치만 있다고 해서 아래 값을 직접 얻었다고 보면 안 된다.

| 데이터 | 판정 |
|---|---|
| red-light delay | 불가능 |
| green time | 불가능 |
| cycle length | 불가능 |
| phase sequence | 불가능 |
| signal offset | 불가능 |
| 실시간 신호 상태 | 불가능 |
| queue discharge rate | 불가능 |

---

## 4. Tensor DB + signal CSV 결합으로 생성 가능한 feature

Step 98에서 만들 수 있는 feature는 다음 범위까지이다.

### 4.1 Node-level signal infrastructure feature

| Feature | 생성 가능성 | causal simulator v2 투입 |
|---|---|---|
| `signal_count_100m` | 가능 | 가능 |
| `signal_count_250m` | 가능 | 가능 |
| `signal_count_500m` | 가능 | 가능 |
| `nearest_signal_distance_m` | 가능 | 가능 |
| `pedestrian_signal_count_250m` | 가능 | 가능 |
| `blink_signal_ratio_250m` | 가능 | 가능 |
| `controlled_signal_ratio_250m` | 가능 | 가능 |
| `signal_density_per_km` | 가능 | 가능 |

### 4.2 Edge-level signal infrastructure feature

| Feature | 생성 가능성 | causal simulator v2 투입 |
|---|---|---|
| `edge_signal_count` | 가능 | 가능 |
| `edge_signal_density_per_km` | 가능 | 가능 |
| `edge_nearest_signal_distance_m` | 가능 | 가능 |
| `edge_pedestrian_signal_count` | 가능 | 가능 |
| `edge_controlled_signal_ratio` | 가능 | 가능 |

단, edge-level feature는 edge geometry가 없으면 `src/dst node 주변 신호의 합성 proxy`로 시작해야 한다.

---

## 5. Proxy로만 가능한 데이터

아래 feature는 실제 측정값이 아니라 proxy로만 허용한다.

| Feature | 의미 | 조건 |
|---|---|---|
| `signal_delay_risk_proxy` | 신호가 많아 지연 위험이 높을 가능성 | 반드시 `_proxy` suffix 유지 |
| `intersection_complexity_proxy` | 교차로/신호 밀집 복잡도 | 실제 교차로 용량으로 주장 금지 |
| `edge_control_complexity_proxy` | edge 주변 제어 인프라 복잡도 | red-light delay로 해석 금지 |
| `stop_access_friction_proxy` | 정류장 접근 마찰도 | 보행 신호 존재 기반 proxy |

---

## 6. 현재 절대 불가능한 데이터

현재 tensor DB + static signal CSV만으로는 아래 데이터를 만들 수 없다.

| 데이터 | 이유 |
|---|---|
| `red_light_delay_seconds` | phase/timing/arrival trajectory 없음 |
| `green_time_seconds` | 신호 현시 자료 없음 |
| `cycle_length_seconds` | 신호 운영 주기 없음 |
| `signal_offset_seconds` | 신호 연동 offset 자료 없음 |
| `real_time_signal_state` | 실시간 신호 상태 없음 |
| `queue_discharge_rate` | 차로별 queue/flow 관측 없음 |
| `lane_level_turning_movement` | 차로·회전 교통량 없음 |
| `actual_vehicle_trajectory` | 버스 GPS(Global Positioning System=위성항법시스템) trajectory 없음 |
| `incident_event_stream` | 사고 이벤트 원천 없음 |
| `weather_event_stream` | 기상 이벤트 원천 없음 |

---

## 7. Causal simulator v2 투입 허용/금지 기준

### 7.1 넣어도 되는 데이터

- tensor DB direct feature
- signal CSV direct static infrastructure feature
- tensor DB + signal CSV 결합으로 만든 static neighborhood feature
- `_proxy` suffix가 붙은 명시적 proxy feature

### 7.2 아직 넣으면 안 되는 데이터

- red-light delay
- green time
- cycle length
- signal phase
- offset
- real-time signal state
- dynamic queue discharge
- phase-aware travel time

---

## 8. Step 98 signal feature builder 입력/출력 contract 초안

### 8.1 입력

| 입력 | 필수 여부 | 설명 |
|---|---|---|
| `--signal-csv` | 필수 | 대구 신호등 CSV 경로 |
| `--db-url` | 선택 | tensor DB DSN(Data Source Name=데이터 원본 이름) |
| `--node-source` | 필수 | node table/view 또는 parquet |
| `--edge-source` | 필수 | edge table/view 또는 parquet |
| `--coord-crs` | 필수 | `EPSG:4326`, `EPSG:5187`, 또는 manual |

### 8.2 출력

| 출력 | 설명 |
|---|---|
| `node_signal_features.parquet` | node-level static signal features |
| `edge_signal_features.parquet` | edge-level static signal features |
| `tensor_signal_feature_contract_v2.json` | feature 정의 및 source hash |
| `signal_feature_quality_report.json` | 결측/좌표/매칭 품질 보고 |

### 8.3 최소 feature set

```text
node_signal_features:
- node_uid
- node_index
- signal_count_250m
- nearest_signal_distance_m
- pedestrian_signal_count_250m
- blink_signal_ratio_250m
- controlled_signal_ratio_250m
- signal_feature_quality_flag

edge_signal_features:
- src_idx
- dst_idx
- edge_signal_count
- edge_signal_density_per_km
- edge_nearest_signal_distance_m
- edge_signal_feature_quality_flag
```

---

## 9. Step 97 최종 판정

현재 신호 CSV는 **동적 신호 phase simulator 원천이 아니라 정적 signal infrastructure feature source**로 사용한다.

따라서 Step 98은 다음처럼 진행한다.

```text
Step 98:
Signal feature builder for causal simulator v2

목표:
signal CSV를 tensor graph node/edge에 결합하여
static signal infrastructure feature를 만든다.

금지:
red-light delay, green time, cycle length, phase, offset을 임의 생성하지 않는다.
```
'@

$AuditPath = Join-Path $AdaptersDir "tensor_signal_data_availability_audit.md"
$AuditMd | Set-Content -Path $AuditPath -Encoding UTF8

# ---------------------------------------------------------------------
# Step 97 file 3:
# 05_training/adapters/inspect_tensor_signal_available_fields.py
# ---------------------------------------------------------------------
$InspectorPy = @'
from __future__ import annotations

import argparse
import csv
import hashlib
import json
import os
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple


CSV_ENCODINGS = ["utf-8-sig", "utf-8", "cp949", "euc-kr"]

LAT_CANDIDATES = [
    "lat", "latitude", "위도", "y_wgs84", "wgs84_y", "위도값"
]
LON_CANDIDATES = [
    "lon", "lng", "longitude", "경도", "x_wgs84", "wgs84_x", "경도값"
]
X_CANDIDATES = [
    "x", "x_coord", "coord_x", "좌표x", "x좌표", "tm_x", "epsg5187_x", "x_5187"
]
Y_CANDIDATES = [
    "y", "y_coord", "coord_y", "좌표y", "y좌표", "tm_y", "epsg5187_y", "y_5187"
]
ID_CANDIDATES = [
    "signal_id", "id", "신호등id", "신호등_id", "시설물관리번호", "관리번호"
]
TYPE_CANDIDATES = [
    "signal_type", "type", "신호등종류", "종류", "시설구분", "신호기종류"
]
NAME_CANDIDATES = [
    "signal_name", "name", "신호등명", "시설명", "교차로명", "설치위치"
]


TENSOR_RELATIONS = [
    ("public", "gatv2_node_master_active"),
    ("public", "gatv2_edge_primary_active"),
    ("public", "gatv2_edge_primary_active_mat"),
    ("public", "gatv2_snapshot_stop_features_train"),
    ("public", "gatv2_snapshot_stop_features_train_mat"),
    ("public", "gatv2_snapshot_summary"),
    ("public", "gatv2_edge_summary"),
]


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1024 * 1024), b""):
            h.update(chunk)
    return h.hexdigest()


def normalize_col(s: str) -> str:
    return str(s).strip().lower().replace(" ", "").replace("-", "_")


def find_first(cols: List[str], candidates: List[str]) -> Optional[str]:
    normalized = {normalize_col(c): c for c in cols}
    for cand in candidates:
        key = normalize_col(cand)
        if key in normalized:
            return normalized[key]
    return None


def read_csv_header_and_sample(path: Path, sample_rows: int = 20) -> Tuple[str, List[str], List[Dict[str, str]], int]:
    last_error: Optional[Exception] = None

    for enc in CSV_ENCODINGS:
        try:
            with open(path, "r", encoding=enc, newline="") as f:
                sample_text = f.read(4096)
                f.seek(0)
                try:
                    dialect = csv.Sniffer().sniff(sample_text)
                except Exception:
                    dialect = csv.excel

                reader = csv.DictReader(f, dialect=dialect)
                cols = list(reader.fieldnames or [])
                rows: List[Dict[str, str]] = []
                total = 0
                for row in reader:
                    total += 1
                    if len(rows) < sample_rows:
                        rows.append(dict(row))
                return enc, cols, rows, total
        except Exception as exc:
            last_error = exc
            continue

    raise RuntimeError(f"failed to read CSV with known encodings: {path}, last_error={last_error}")


def inspect_signal_csv(path: Optional[Path]) -> Dict[str, Any]:
    if path is None:
        return {
            "provided": False,
            "status": "not_provided",
            "note": "No signal CSV path was supplied. Document/contract self-test can still pass."
        }

    if not path.exists():
        return {
            "provided": True,
            "path": str(path),
            "status": "missing",
            "error": "signal CSV file does not exist"
        }

    enc, cols, rows, row_count = read_csv_header_and_sample(path)
    lat_col = find_first(cols, LAT_CANDIDATES)
    lon_col = find_first(cols, LON_CANDIDATES)
    x_col = find_first(cols, X_CANDIDATES)
    y_col = find_first(cols, Y_CANDIDATES)
    id_col = find_first(cols, ID_CANDIDATES)
    type_col = find_first(cols, TYPE_CANDIDATES)
    name_col = find_first(cols, NAME_CANDIDATES)

    coordinate_mode = "unknown"
    if lat_col and lon_col:
        coordinate_mode = "wgs84_lat_lon"
    elif x_col and y_col:
        coordinate_mode = "projected_x_y"

    inferred = {
        "id_col": id_col,
        "type_col": type_col,
        "name_col": name_col,
        "lat_col": lat_col,
        "lon_col": lon_col,
        "x_col": x_col,
        "y_col": y_col,
        "coordinate_mode": coordinate_mode
    }

    direct_features = []
    if id_col:
        direct_features.append("signal_id")
    if type_col:
        direct_features.append("signal_type")
    if name_col:
        direct_features.append("signal_name")
    if lat_col and lon_col:
        direct_features.extend(["latitude", "longitude"])
    if x_col and y_col:
        direct_features.extend(["x_coord", "y_coord"])

    possible_flag_features = []
    joined_cols = " ".join(cols)
    if any(k in joined_cols for k in ["보행", "pedestrian"]):
        possible_flag_features.append("pedestrian_signal_flag_candidate")
    if any(k in joined_cols for k in ["점멸", "blink"]):
        possible_flag_features.append("blink_signal_flag_candidate")
    if any(k in joined_cols for k in ["제어", "control", "controlled"]):
        possible_flag_features.append("controlled_signal_flag_candidate")

    return {
        "provided": True,
        "path": str(path),
        "status": "ok",
        "sha256": sha256_file(path),
        "encoding": enc,
        "row_count": int(row_count),
        "column_count": int(len(cols)),
        "columns": cols,
        "inferred_columns": inferred,
        "direct_signal_features_available": direct_features,
        "possible_flag_features": possible_flag_features,
        "sample_rows": rows[:3],
        "admission": {
            "static_signal_infrastructure_allowed": coordinate_mode != "unknown",
            "dynamic_signal_phase_allowed": False,
            "red_light_delay_allowed": False,
            "green_time_allowed": False
        },
        "warnings": [] if coordinate_mode != "unknown" else [
            "No coordinate columns were confidently inferred. Step 98 spatial join requires manual column mapping."
        ]
    }


def build_db_url_from_env() -> Optional[str]:
    if os.environ.get("URBANBUS_DB_DSN"):
        return os.environ["URBANBUS_DB_DSN"]

    host = os.environ.get("PGHOST")
    db = os.environ.get("PGDATABASE")
    user = os.environ.get("PGUSER")
    pw = os.environ.get("PGPASSWORD")
    port = os.environ.get("PGPORT", "5432")
    if host and db and user:
        if pw:
            return f"postgresql://{user}:{pw}@{host}:{port}/{db}"
        return f"postgresql://{user}@{host}:{port}/{db}"
    return None


def inspect_tensor_db(db_url: Optional[str]) -> Dict[str, Any]:
    if not db_url:
        return {
            "provided": False,
            "status": "not_provided",
            "note": "No DB URL supplied. Set --db-url or URBANBUS_DB_DSN to inspect tensor DB fields."
        }

    try:
        import psycopg2
        import psycopg2.extras
    except Exception as exc:
        return {
            "provided": True,
            "status": "dependency_missing",
            "error": f"psycopg2 not importable: {exc}"
        }

    out: Dict[str, Any] = {
        "provided": True,
        "status": "ok",
        "relations": {}
    }

    try:
        conn = psycopg2.connect(db_url)
        try:
            with conn.cursor(cursor_factory=psycopg2.extras.RealDictCursor) as cur:
                for schema, rel in TENSOR_RELATIONS:
                    cur.execute(
                        """
                        SELECT 1
                        FROM information_schema.tables
                        WHERE table_schema = %s
                          AND table_name = %s
                        LIMIT 1
                        """,
                        (schema, rel),
                    )
                    exists = cur.fetchone() is not None

                    payload: Dict[str, Any] = {"exists": bool(exists)}
                    if exists:
                        cur.execute(
                            """
                            SELECT column_name, data_type
                            FROM information_schema.columns
                            WHERE table_schema = %s
                              AND table_name = %s
                            ORDER BY ordinal_position
                            """,
                            (schema, rel),
                        )
                        cols = cur.fetchall()
                        payload["columns"] = [
                            {"name": r["column_name"], "data_type": r["data_type"]}
                            for r in cols
                        ]

                        try:
                            cur.execute(f'SELECT COUNT(*) AS n FROM "{schema}"."{rel}"')
                            payload["row_count"] = int(cur.fetchone()["n"])
                        except Exception as exc:
                            payload["row_count_error"] = str(exc)

                    out["relations"][f"{schema}.{rel}"] = payload
        finally:
            conn.close()
    except Exception as exc:
        return {
            "provided": True,
            "status": "connection_failed",
            "error": str(exc)
        }

    return out


def classify_availability(signal_report: Dict[str, Any], tensor_report: Dict[str, Any]) -> Dict[str, Any]:
    tensor_direct = [
        "node_uid",
        "node_index",
        "src_idx",
        "dst_idx",
        "distance_m",
        "time_sec",
        "generalized_cost",
        "long_edge_5km_flag",
        "state_ts",
        "next_state_ts",
        "boardings_recent_log",
        "alightings_recent_log",
        "waiting_passenger_cnt_log",
        "hour_sin",
        "hour_cos",
        "is_peak",
        "next_boardings_recent",
        "next_alightings_recent",
        "next_waiting_passenger_cnt"
    ]

    signal_direct = signal_report.get("direct_signal_features_available", [])

    derived_possible = []
    coord_ok = (
        signal_report.get("status") == "ok"
        and signal_report.get("inferred_columns", {}).get("coordinate_mode") != "unknown"
    )
    if coord_ok:
        derived_possible = [
            "signal_count_100m",
            "signal_count_250m",
            "signal_count_500m",
            "signal_density_per_km",
            "nearest_signal_distance_m",
            "pedestrian_signal_count_250m",
            "blink_signal_ratio_250m",
            "controlled_signal_ratio_250m",
            "edge_signal_count",
            "edge_signal_density_per_km",
            "edge_nearest_signal_distance_m"
        ]

    proxy_only = [
        "signal_delay_risk_proxy",
        "intersection_complexity_proxy",
        "edge_control_complexity_proxy",
        "stop_access_friction_proxy"
    ]

    unavailable = [
        "red_light_delay_seconds",
        "green_time_seconds",
        "cycle_length_seconds",
        "phase_sequence",
        "signal_offset_seconds",
        "real_time_signal_state",
        "queue_discharge_rate",
        "lane_level_turning_movement",
        "actual_vehicle_trajectory",
        "incident_event_stream",
        "weather_event_stream"
    ]

    return {
        "tensor_db_direct": tensor_direct,
        "signal_csv_direct": signal_direct,
        "tensor_db_plus_signal_csv_derived": derived_possible,
        "proxy_only": proxy_only,
        "currently_unavailable": unavailable,
        "causal_simulator_v2_admission": {
            "allowed_now": [
                "tensor_db_direct",
                "signal_csv_direct_static_fields",
                "derived_static_signal_infrastructure_features",
                "explicit_proxy_features"
            ],
            "not_allowed_now": [
                "dynamic_signal_phase",
                "red_light_delay",
                "green_time",
                "cycle_length",
                "signal_offset",
                "real_time_signal_state"
            ]
        },
        "step_98_ready": bool(coord_ok),
        "step_98_blockers": [] if coord_ok else [
            "Signal CSV coordinate columns were not inferred. Provide explicit column mapping before spatial feature build."
        ]
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--signal-csv", default="", help="Path to Daegu signal CSV")
    parser.add_argument("--db-url", default="", help="PostgreSQL DSN. If omitted, URBANBUS_DB_DSN or PG* env vars are used.")
    parser.add_argument("--output-json", default="artifacts/step97_tensor_signal_data_availability_audit_report.json")
    args = parser.parse_args()

    signal_path = Path(args.signal_csv) if args.signal_csv else None
    db_url = args.db_url or build_db_url_from_env()

    signal_report = inspect_signal_csv(signal_path)
    tensor_report = inspect_tensor_db(db_url)
    classification = classify_availability(signal_report, tensor_report)

    report = {
        "artifact_version": "tensor_signal_data_availability_audit_report_v1",
        "step": 97,
        "signal_csv_report": signal_report,
        "tensor_db_report": tensor_report,
        "availability_classification": classification,
        "claim_guardrails": {
            "trained_model": False,
            "performance_claim_allowed": False,
            "causal_performance_claim_allowed": False,
            "smoke_only": True
        }
    }

    out_path = Path(args.output_json)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")

    print("[OK] Step 97 tensor + signal availability audit report written")
    print(f"[OK] output_json : {out_path}")
    print(f"[OK] signal_csv  : {signal_report.get('status')}")
    print(f"[OK] tensor_db   : {tensor_report.get('status')}")
    print(f"[OK] step98_ready: {classification.get('step_98_ready')}")
    if classification.get("step_98_blockers"):
        print("[WARN] Step 98 blockers:")
        for b in classification["step_98_blockers"]:
            print(f"  - {b}")


if __name__ == "__main__":
    main()
'@

$InspectorPath = Join-Path $AdaptersDir "inspect_tensor_signal_available_fields.py"
$InspectorPy | Set-Content -Path $InspectorPath -Encoding UTF8

# ---------------------------------------------------------------------
# Step 97 file 4:
# 05_training/adapters/test_tensor_signal_data_availability_audit.py
# ---------------------------------------------------------------------
$TestPy = @'
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
ADAPTERS_DIR = PROJECT_ROOT / "05_training" / "adapters"

AUDIT_MD = ADAPTERS_DIR / "tensor_signal_data_availability_audit.md"
REQ_JSON = ADAPTERS_DIR / "tensor_signal_data_requirements_v2.json"
INSPECTOR = ADAPTERS_DIR / "inspect_tensor_signal_available_fields.py"


def assert_true(cond: bool, msg: str) -> None:
    if not cond:
        raise AssertionError(msg)


def test_files_exist() -> None:
    assert_true(AUDIT_MD.exists(), f"missing: {AUDIT_MD}")
    assert_true(REQ_JSON.exists(), f"missing: {REQ_JSON}")
    assert_true(INSPECTOR.exists(), f"missing: {INSPECTOR}")


def test_requirements_json_contract() -> None:
    payload = json.loads(REQ_JSON.read_text(encoding="utf-8-sig"))
    assert_true(payload["artifact_version"] == "tensor_signal_data_requirements_v2", "bad artifact_version")
    assert_true(payload["step"] == 97, "bad step")

    source_classes = payload.get("source_classes", {})
    for key in [
        "tensor_db_direct",
        "signal_csv_direct",
        "tensor_db_plus_signal_csv_derived",
        "proxy_only",
        "currently_unavailable",
    ]:
        assert_true(key in source_classes, f"missing source class: {key}")

    unavailable = source_classes["currently_unavailable"]["examples"]
    for forbidden in [
        "red_light_delay_seconds",
        "green_time_seconds",
        "cycle_length_seconds",
        "phase_sequence",
        "signal_offset_seconds",
    ]:
        assert_true(forbidden in unavailable, f"missing unavailable field: {forbidden}")

    rules = payload.get("causal_simulator_v2_admission_rules", {})
    assert_true("currently_unavailable" in rules.get("reject", []), "currently_unavailable must be rejected")


def test_audit_md_keywords() -> None:
    text = AUDIT_MD.read_text(encoding="utf-8-sig")
    required_phrases = [
        "toy causal smoke validation",
        "trained_model",
        "performance_claim_allowed",
        "signal_count_250m",
        "nearest_signal_distance_m",
        "red-light delay",
        "green time",
        "cycle length",
        "Step 98",
        "static signal infrastructure"
    ]
    for phrase in required_phrases:
        assert_true(phrase in text, f"missing phrase in audit md: {phrase}")


def test_inspector_runs_without_inputs() -> None:
    out_json = PROJECT_ROOT / "artifacts" / "step97_selftest" / "audit_report_no_inputs.json"
    if out_json.exists():
        out_json.unlink()

    cmd = [
        sys.executable,
        str(INSPECTOR),
        "--output-json",
        str(out_json),
    ]
    completed = subprocess.run(cmd, cwd=str(PROJECT_ROOT), text=True, capture_output=True)

    if completed.returncode != 0:
        print(completed.stdout)
        print(completed.stderr)
        raise AssertionError("inspector failed without optional inputs")

    assert_true(out_json.exists(), "inspector did not write output json")
    payload = json.loads(out_json.read_text(encoding="utf-8"))
    assert_true(payload["step"] == 97, "bad report step")
    assert_true(payload["claim_guardrails"]["performance_claim_allowed"] is False, "claim guardrail broken")

    cls = payload["availability_classification"]
    assert_true("red_light_delay_seconds" in cls["currently_unavailable"], "red_light_delay must be unavailable")
    assert_true(cls["causal_simulator_v2_admission"]["not_allowed_now"], "not_allowed_now must not be empty")


def main() -> None:
    test_files_exist()
    test_requirements_json_contract()
    test_audit_md_keywords()
    test_inspector_runs_without_inputs()
    print("[OK] Step 97 tensor + signal data availability audit self-test PASS")


if __name__ == "__main__":
    main()
'@

$TestPath = Join-Path $AdaptersDir "test_tensor_signal_data_availability_audit.py"
$TestPy | Set-Content -Path $TestPath -Encoding UTF8

Write-Host "[OK] Step 97 files created:"
Write-Host " - $AuditPath"
Write-Host " - $RequirementsPath"
Write-Host " - $InspectorPath"
Write-Host " - $TestPath"

if ($RunSelfTest) {
    if (Test-Path ".\05_training\.venv\Scripts\python.exe") {
        $py = (Resolve-Path ".\05_training\.venv\Scripts\python.exe").Path
    } else {
        $py = "python"
    }

    Write-Host "[INFO] python = $py"

    & $py -m py_compile `
      ".\05_training\adapters\inspect_tensor_signal_available_fields.py" `
      ".\05_training\adapters\test_tensor_signal_data_availability_audit.py"

    if ($LASTEXITCODE -ne 0) {
        throw "[FAIL] Step 97 py_compile failed"
    }

    & $py ".\05_training\adapters\test_tensor_signal_data_availability_audit.py"

    if ($LASTEXITCODE -ne 0) {
        throw "[FAIL] Step 97 self-test failed"
    }

    Write-Host "[DONE] Step 97 Tensor DB + signal CSV data availability audit complete."
}
