#!/usr/bin/env python3
"""H4M-AE-R9.8 LS3-CR0/CR1 joint-assignment credit contract and rollout buffer.

Reward V2 is not touched.  This is a new attribution layer *over* frozen Reward
V2 outputs: it decides which already-computed rewards belong to which assignment
decision, and nothing about how those rewards are computed.

Team reward
-----------
    team_reward_t = mean( RewardV2_t(agent_i) for active agent_i )

Arithmetic mean over *active* agents only, so the scale does not drift with fleet
size and idle vehicles do not dilute the signal.  An assignment transition with
zero active agents is an error, not a zero: the contract fails closed rather than
quietly inventing a reward.

Assignment interval
-------------------
Assignment decisions are coarser than operational transitions, so credit runs
over the half-open interval between consecutive decisions:

    R_assign_k     = sum_j gamma^j * team_reward_(T_k + j)
    Gamma_assign_k = gamma ^ delta_operational_steps_k

This is a semi-Markov high-level decision process.  Where the runtime happens to
take exactly one operational step per assignment, delta is 1 and the whole thing
collapses to ordinary PPO credit -- no cadence is changed to make that true.

Frozen action support
---------------------
PPO's ratio is only meaningful if the behaviour policy and the update policy saw
the same action set.  The safe set is therefore *rollout evidence*: it is stored
with the transition and replayed, never regenerated by re-running Local Search or
Zero-Loss.  Regeneration could change the candidate count, the mask, or the
denominator, and would silently invalidate every ratio computed from it.

Forced rows
-----------
When only NO_ASSIGN is legal there is no choice to learn from: log-prob is
identically 0 and the policy gradient is structurally zero.  Those rows carry
`forced_action = True`, contribute nothing to actor or entropy loss, and are
excluded from the actor denominator -- but they still carry reward, return and
value, because the state is still informative for the critic.
"""

from __future__ import annotations

import hashlib
import json
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Sequence, Tuple

CONTRACT_ID = "JOINT_ASSIGNMENT_CREDIT_CONTRACT_V1"
CONTRACT_VERSION = "LS3_CR0_V1"

TEAM_REWARD_RULE = "ACTIVE_AGENT_MEAN_OF_FROZEN_REWARD_V2"
NO_ASSIGN = "NO_ASSIGN_KEEP_CURRENT_PLANS"

# Resolved from the repository, not invented here.
GAMMA = 0.99
GAE_LAMBDA = 0.95
PPO_CLIP_EPSILON = 0.2
REWARD_V2_FREEZE_SHA = "966d3d8b091b87b033d2203cfb721983a5e66f77fe247e42885153a3b7fc3161"
REWARD_V2_RUNTIME_BINDING_SHA = "3514bdd492cdf389e959445b1b50b53b4215bcd28d090e8b416c422b9fcd17c3"
ZERO_LOSS_EPSILON_SEC = 0.0

CREDIT_CONTRACT = {
    "contract_id": CONTRACT_ID, "version": CONTRACT_VERSION,
    "reward_v2_modified": False,
    "reward_v2_freeze_sha256": REWARD_V2_FREEZE_SHA,
    "reward_v2_runtime_binding_sha256": REWARD_V2_RUNTIME_BINDING_SHA,
    "layer": "new credit attribution over frozen Reward V2 outputs",
    "team_reward": {
        "rule": TEAM_REWARD_RULE,
        "formula": "team_reward_t = mean(RewardV2_t(agent_i) for active agent_i)",
        "aggregation": "arithmetic mean",
        "sum_used": False,
        "inactive_agents_included": False,
        "fleet_size_multiplication": False,
        "selected_agent_only_reward": False,
        "manually_mixed_local_global": False,
        "zero_active_agents": "fail closed, never defined as zero reward",
    },
    "assignment_interval": {
        "definition": "[T_k, T_(k+1)) or to episode/window termination",
        "discounted_return": "R_assign_k = sum_j gamma^j * team_reward_(T_k+j)",
        "bootstrap_discount": "Gamma_assign_k = gamma ** delta_operational_steps_k",
        "process": "semi-Markov high-level decision process",
        "reduces_to_ordinary_ppo_when_delta_is_1": True,
        "simulator_cadence_altered": False,
    },
    "discount": {"gamma": GAMMA, "gae_lambda": GAE_LAMBDA,
                 "source": "existing authoritative MAPPO configuration", "invented": False},
    "advantage_ownership": {
        "separate_from_operational": True,
        "shared_advantage_storage": False,
        "operational_advantage_reused": False,
        "tensors": ["assignment_return", "assignment_value", "assignment_td_residual",
                    "assignment_advantage", "assignment_gae"],
    },
    "optimizer_ownership": {
        "joint_assignment_actor_optimizer": "separate",
        "joint_assignment_critic_optimizer": "separate",
        "shared_with_gatv2": False,
        "shared_with_operational_actor": False,
        "shared_with_operational_critic": False,
        "frozen_during_joint_training": ["gatv2", "operational_actor", "operational_critic"],
    },
    "critic_ownership": {
        "critic": "JointAssignmentCritic",
        "predicts": "V_joint(S_k) before assignment selection",
        "may_consume": ["gatv2 global context", "active agent states", "fleet context",
                        "decision-group demand context", "safe-candidate-set summary"],
        "must_not_consume": ["selected agent_id", "selected candidate_id",
                             "post-selection action identity", "future reward",
                             "future simulator state"],
        "selected_action_leakage": False,
    },
    "forced_action": {
        "rule": "valid_action_count == 1 implies forced_action",
        "actor_policy_loss_weight": 0.0, "entropy_loss_weight": 0.0,
        "critic_loss_weight": 1.0,
        "reward_accounting_active": True, "return_and_gae_accounting_active": True,
        "excluded_from_actor_denominator": True,
        "zero_policy_gradient_is_architecture_failure": False,
    },
    "no_assign": {
        "always_in_action_set": True,
        "learnable_when_safe_options_exist": True,
        "hardcoded_as_inferior": False,
    },
    "safe_set_replay": {
        "source": "frozen rollout evidence",
        "regenerated_at_update": False,
        "local_search_rerun_at_update": False,
        "zero_loss_rerun_at_update": False,
        "assertion": "behavior_action_support_digest == update_action_support_digest",
    },
    "zero_loss": {"epsilon_sec": ZERO_LOSS_EPSILON_SEC, "role": "hard feasibility mask",
                  "as_reward": False, "as_soft_penalty": False, "learnable": False,
                  "unsafe_probability": 0.0},
    "p95_wait": {"status": "evaluation only", "used_as_training_reward": False},
    "boundary": {"gae_resets_at": ["episode boundary", "window boundary", "terminated", "truncated"],
                 "cross_window_bootstrap": False},
    "ppo": {"clip_epsilon": PPO_CLIP_EPSILON, "source": "existing authoritative MAPPO configuration"},
    "reward_normalization": {
        "authoritative_algorithm": "mappo_runner.RewardNormalizer",
        "parameters": {"window_size": 1000, "clip_value": 10.0},
        "state_shared_with_operational_actor": False,
        "separate_assignment_normalization_state": True,
        "new_clipping_values": False, "manual_rescaling": False,
    },
    "python_builtin_hash_used": False,
}


class CreditContractError(RuntimeError):
    def __init__(self, code: str, detail: str = "") -> None:
        super().__init__(f"{code}: {detail}" if detail else code)
        self.code = code


def contract_digest() -> str:
    return hashlib.sha256(json.dumps(CREDIT_CONTRACT, sort_keys=True).encode("utf-8")).hexdigest()


def team_reward(agent_rewards: Sequence[float], active_mask: Sequence[bool]) -> float:
    """Active-agent mean of frozen Reward V2 outputs.

    Fails closed on zero active agents: a transition with nobody active is a
    contract violation, not a zero-reward sample.
    """
    if len(agent_rewards) != len(active_mask):
        raise CreditContractError("REWARD_ACTIVE_MASK_LENGTH_MISMATCH",
                                  f"{len(agent_rewards)} != {len(active_mask)}")
    active = [float(r) for r, a in zip(agent_rewards, active_mask) if a]
    if not active:
        raise CreditContractError("ZERO_ACTIVE_AGENTS_AT_ASSIGNMENT_TRANSITION",
                                  "team reward is undefined; it is not zero")
    return sum(active) / len(active)


def assignment_return(team_rewards: Sequence[float], gamma: float = GAMMA) -> float:
    """Discounted team reward accumulated inside one assignment interval."""
    return sum((gamma ** j) * float(r) for j, r in enumerate(team_rewards))


def bootstrap_discount(delta_operational_steps: int, gamma: float = GAMMA) -> float:
    """Duration-aware bootstrap factor for a semi-Markov high-level step."""
    if delta_operational_steps < 1:
        raise CreditContractError("NON_POSITIVE_ASSIGNMENT_DURATION", str(delta_operational_steps))
    return gamma ** int(delta_operational_steps)


def action_support_digest(pair_ids: Sequence[Tuple[str, str]], *, no_assign_index: int) -> str:
    """Identity-based digest of the action support.

    Canonical ordering comes from identity, so two runs that present the same
    pairs in different row order produce the same digest -- which is exactly what
    makes the PPO ratio comparable.
    """
    ordered = sorted((str(a), str(c)) for a, c in pair_ids)
    payload = json.dumps({"pairs": ordered, "no_assign": NO_ASSIGN,
                          "no_assign_index": int(no_assign_index)}, sort_keys=True)
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


@dataclass
class AssignmentTransition:
    """One high-level assignment decision and the credit that belongs to it."""

    assignment_step_id: str
    decision_group_id: str
    episode_id: str
    window_id: str
    decision_ts: int
    next_assignment_ts: Optional[int]
    delta_operational_steps: int
    pre_state_digest: str
    next_state_digest: Optional[str]
    safe_pair_ids: List[Tuple[str, str]]
    safe_pair_mask: List[bool]
    no_assign_index: int
    selected_agent_id: Optional[str]
    selected_candidate_id: Optional[str]
    selected_is_no_assign: bool
    valid_action_count: int
    forced_action: bool
    old_log_prob: float
    old_value: float
    team_reward_sequence: List[float]
    assignment_discounted_reward: float
    terminated: bool
    truncated: bool
    policy_version: str
    credit_contract_version: str
    seed: int
    provenance: Dict[str, Any] = field(default_factory=dict)

    def __post_init__(self) -> None:
        if len(self.safe_pair_mask) != len(self.safe_pair_ids):
            raise CreditContractError("SAFE_MASK_LENGTH_MISMATCH")
        if any(not m for m in self.safe_pair_mask):
            raise CreditContractError("UNSAFE_PAIR_IN_STORED_ACTION_SUPPORT",
                                      "rejected candidates are audit evidence, never selectable")
        expected = len(self.safe_pair_ids) + 1
        if self.valid_action_count != expected:
            raise CreditContractError("VALID_ACTION_COUNT_MISMATCH",
                                      f"{self.valid_action_count} != {expected}")
        if self.forced_action != (self.valid_action_count == 1):
            raise CreditContractError("FORCED_ACTION_FLAG_MISMATCH")
        if self.forced_action and not self.selected_is_no_assign:
            raise CreditContractError("FORCED_ROW_MUST_SELECT_NO_ASSIGN")
        if self.selected_is_no_assign and (self.selected_agent_id or self.selected_candidate_id):
            raise CreditContractError("NO_ASSIGN_ROW_CARRIES_A_SELECTED_PAIR")
        if not self.selected_is_no_assign:
            key = (str(self.selected_agent_id), str(self.selected_candidate_id))
            if key not in [(str(a), str(c)) for a, c in self.safe_pair_ids]:
                raise CreditContractError("SELECTED_PAIR_NOT_IN_SAFE_SUPPORT", str(key))

    @property
    def action_support_digest(self) -> str:
        return action_support_digest(self.safe_pair_ids, no_assign_index=self.no_assign_index)

    @property
    def action_index(self) -> int:
        if self.selected_is_no_assign:
            return self.no_assign_index
        ordered = sorted((str(a), str(c)) for a, c in self.safe_pair_ids)
        return ordered.index((str(self.selected_agent_id), str(self.selected_candidate_id)))

    def payload(self) -> Dict[str, Any]:
        return {
            "assignment_step_id": self.assignment_step_id,
            "decision_group_id": self.decision_group_id,
            "episode_id": self.episode_id, "window_id": self.window_id,
            "decision_ts": self.decision_ts, "next_assignment_ts": self.next_assignment_ts,
            "delta_operational_steps": self.delta_operational_steps,
            "pre_state_digest": self.pre_state_digest, "next_state_digest": self.next_state_digest,
            "safe_pair_ids": [list(p) for p in self.safe_pair_ids],
            "safe_pair_count": len(self.safe_pair_ids),
            "no_assign_index": self.no_assign_index,
            "action_support_digest": self.action_support_digest,
            "selected_agent_id": self.selected_agent_id,
            "selected_candidate_id": self.selected_candidate_id,
            "selected_is_no_assign": self.selected_is_no_assign,
            "action_index": self.action_index,
            "valid_action_count": self.valid_action_count, "forced_action": self.forced_action,
            "old_log_prob": self.old_log_prob, "old_value": self.old_value,
            "team_reward_sequence": list(self.team_reward_sequence),
            "assignment_discounted_reward": self.assignment_discounted_reward,
            "terminated": self.terminated, "truncated": self.truncated,
            "policy_version": self.policy_version,
            "credit_contract_version": self.credit_contract_version,
            "seed": self.seed, "provenance": dict(self.provenance),
        }


@dataclass
class AssignmentRolloutBuffer:
    """Assignment transitions, kept separate from any operational rollout storage."""

    transitions: List[AssignmentTransition] = field(default_factory=list)
    shared_advantage_storage: bool = False

    def add(self, transition: AssignmentTransition) -> None:
        self.transitions.append(transition)

    def __len__(self) -> int:
        return len(self.transitions)

    def by_window(self) -> Dict[str, List[AssignmentTransition]]:
        out: Dict[str, List[AssignmentTransition]] = {}
        for t in self.transitions:
            out.setdefault(t.window_id, []).append(t)
        return out

    def assert_action_support_unchanged(self, update_supports: Sequence[str]) -> Dict[str, Any]:
        """PPO replay must see the exact support the behaviour policy saw."""
        if len(update_supports) != len(self.transitions):
            raise CreditContractError("ACTION_SUPPORT_COUNT_MISMATCH")
        mismatched = [t.assignment_step_id for t, d in zip(self.transitions, update_supports)
                      if t.action_support_digest != d]
        if mismatched:
            raise CreditContractError("ACTION_SUPPORT_MUTATED_BETWEEN_ROLLOUT_AND_UPDATE",
                                      str(mismatched[:3]))
        return {"checked": len(self.transitions), "mismatched": 0,
                "behavior_equals_update_support": True}

    def stats(self) -> Dict[str, Any]:
        forced = [t for t in self.transitions if t.forced_action]
        return {
            "transitions": len(self.transitions),
            "forced_rows": len(forced),
            "non_forced_rows": len(self.transitions) - len(forced),
            "windows": len(self.by_window()),
            "no_assign_rows": sum(1 for t in self.transitions if t.selected_is_no_assign),
            "safe_pair_counts": sorted({len(t.safe_pair_ids) for t in self.transitions}),
            "shared_advantage_storage": self.shared_advantage_storage,
            "unsafe_rows_in_support": 0,
        }
